# site details
title: Alexandre Teles
tag_line: O estranho misterioso
description: "No one ever discovers the dephts of his own loneliness..."
keywords: alexteles alexandre teles kabbalista afterSt0rm
url: https://alexteles.com
author: Alexandre Teles
author_url: http://alexteles.com

# preferences
markdown: kramdown
highlighter: rouge
timezone: America/Bahia

# kramdown preferences
kramdown:
  input: GFM

# plugins
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

# building
lsi: false
incremental: false

# exclusions
exclude: [README.md]

# collections
collections:
  category:
    output: true

# defaults
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# jekyll-assets
source_maps: false
compression: true
gzip: false
caching:
  path: ".jekyll-cache/assets"
  type: file
  enabled: false

# jekyll-minifier
  preserve_php: false
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: true
  compress_css: true
  compress_javascript: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: true
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: true